## Estadística Aplicada
Sesión 2 - 11 agosto

Cecilia Sarahí Gutiérrez Padilla Gpo 43

In [75]:
7 > 5

True

In [76]:
7 > 10

False

In [77]:
7 > 10 & 7 > 5

False

## Lista
Una lista en pyhton es una colección de objetos (mismo tipo o distinto tipo)

NombreLista = [objeto1, objeto2, objeto3, etc]

In [78]:
alumno1 = ['Juan', 'Perez', 17]

In [79]:
type(alumno1)

list

In [80]:
alumno1

['Juan', 'Perez', 17]

In [81]:
estadistica_g43 = ['andrea','sofia', 'ana', 'luis']

In [82]:
estadistica_g43

['andrea', 'sofia', 'ana', 'luis']

In [83]:
#elegir sofia
estadistica_g43[1]

'sofia'

In [84]:
#elegir luis
estadistica_g43[3]

'luis'

In [85]:
## ana se da de baja
estadistica_g43.remove('ana')

In [86]:
estadistica_g43

['andrea', 'sofia', 'luis']

In [87]:
##jorge se dio de alta
estadistica_g43.append('jorge')

In [88]:
estadistica_g43

['andrea', 'sofia', 'luis', 'jorge']

In [89]:
yo_enFCFM = ['cecilia', 'LA', 7, 89]

In [90]:
yo_enFCFM


['cecilia', 'LA', 7, 89]

In [91]:
mi_carrera=yo_enFCFM[1]
mi_promedio=yo_enFCFM[3]


In [92]:
print('yo estudio en', mi_carrera, 'tengo un prommedio de', mi_promedio)

yo estudio en LA tengo un prommedio de 89


## Librerías/Paquetes/Modulos

Una librería en python es un cojunto de códigos que le indican a python cómo hacer dereterminadas cosas

Para poder usar una librería: 1ero hay que instalarla (una vez) y 2do hay que decirle a python que la use

In [93]:
# instalar una librería yahoo finanzas
!pip install yfinance

"pip" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.


In [94]:
import yfinance

In [95]:
yfinance.download('APPl')

[*********************100%***********************]  1 of 1 completed


1 Failed download:
['APPL']: Exception('%ticker%: No price data found, symbol may be delisted (1d 1924-09-03 -> 2023-08-11)')


Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [96]:
import yfinance as yf

In [97]:
yf.download('APPl')

[*********************100%***********************]  1 of 1 completed


1 Failed download:
['APPL']: Exception('%ticker%: No price data found, symbol may be delisted (1d 1924-09-03 -> 2023-08-11)')


Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

## Numpy

La estructura básica de numpy son los arreglos (arrays). Un arreglo es una colección de objetos del mismo tipo

Vamos a suponer que sabemos cuantas botellas de agua vende la cafetería. Lunes 28, Martes 33, Miércoles 44, Jueves 40, Viernes 31

In [98]:
ventas=[28,33,44,40,31]

In [99]:
type(ventas)

list

In [100]:
#use numpy
import numpy as np

In [101]:
ventas= np.array(ventas)

In [102]:
type(ventas)

numpy.ndarray

In [103]:
#sumar
np.sum(ventas)

176

In [104]:
print('las ventas totales de la semana son', np.sum(ventas))

las ventas totales de la semana son 176


In [105]:
#multiplicar
np.prod(ventas)

50413440

In [106]:
#valor maximo
np.max(ventas)

44

In [107]:
#valor minimo
np.min(ventas)

28

In [108]:
#ordenar de menor a mayor
np.sort(ventas)

array([28, 31, 33, 40, 44])

In [109]:
#media
np.mean(ventas)

35.2

In [110]:
#varianza poblacional
np.var(ventas, ddof=0)


34.959999999999994

In [111]:
#varianza 
np.var(ventas)

34.959999999999994

In [112]:
#desviación estándar poblacional
np.std(ventas)

5.912698199637792

In [113]:
#varianza muestral
np.var(ventas, ddof=1)

43.699999999999996

In [114]:
#desviación estándar muestral
np.std(ventas, ddof= 1)

6.6105975524153635

In [116]:
##vectors
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [117]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [120]:
np.arange(0, 100, 15)

array([ 0, 15, 30, 45, 60, 75, 90])

In [121]:
np.random.randint(0,15, 10)

array([ 8, 13,  3,  9,  1, 10,  3, 13,  3,  2])

In [124]:
#aleatorios de una dist uniforme
#semilla
np.random.seed(12)
aleatorios= np.random.randint(0,15,10)

In [125]:
aleatorios

array([11, 11,  6, 13,  1,  2,  3,  3, 12,  0])

In [126]:
aleatorios= np.sort(aleatorios)

In [127]:
aleatorios

array([ 0,  1,  2,  3,  3,  6, 11, 11, 12, 13])

In [128]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [129]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [130]:
np.full(6,8)

array([8, 8, 8, 8, 8, 8])

¿Cuántos minutos hay en un mes?
lista=[30,24,60]

In [131]:
lista= [30,24,60]
lista=np.array(lista)
np.prod(lista)

43200

# función vs método

In [132]:
numeros= [1.4567, 4.568, 10.375]

1. Arreglo
2. Calcular la media
3. Redondear a decimales

In [133]:
#funcion
round (np.mean ( np.array(numeros) ),2)

5.47

In [135]:
#método
np.array(numeros).mean().round(2)

5.47